version: "3.0"

services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app/nexoos-challenge:cached
    ports:
      - "3000:3000"
      - "3035:3035"
    depends_on:
      - db
    env_file:
      - .env.development

  db:
    image: postgres:12.1
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env.development

volumes:
  postgres-data:
