 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/telephones", type: :request do
  # Telephone. As you add validations to Telephone, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Telephone.create! valid_attributes
      get telephones_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      telephone = Telephone.create! valid_attributes
      get telephone_url(telephone)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_telephone_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      telephone = Telephone.create! valid_attributes
      get edit_telephone_url(telephone)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Telephone" do
        expect {
          post telephones_url, params: { telephone: valid_attributes }
        }.to change(Telephone, :count).by(1)
      end

      it "redirects to the created telephone" do
        post telephones_url, params: { telephone: valid_attributes }
        expect(response).to redirect_to(telephone_url(Telephone.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Telephone" do
        expect {
          post telephones_url, params: { telephone: invalid_attributes }
        }.to change(Telephone, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post telephones_url, params: { telephone: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested telephone" do
        telephone = Telephone.create! valid_attributes
        patch telephone_url(telephone), params: { telephone: new_attributes }
        telephone.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the telephone" do
        telephone = Telephone.create! valid_attributes
        patch telephone_url(telephone), params: { telephone: new_attributes }
        telephone.reload
        expect(response).to redirect_to(telephone_url(telephone))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        telephone = Telephone.create! valid_attributes
        patch telephone_url(telephone), params: { telephone: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested telephone" do
      telephone = Telephone.create! valid_attributes
      expect {
        delete telephone_url(telephone)
      }.to change(Telephone, :count).by(-1)
    end

    it "redirects to the telephones list" do
      telephone = Telephone.create! valid_attributes
      delete telephone_url(telephone)
      expect(response).to redirect_to(telephones_url)
    end
  end
end
